ERROR - 2024-01-30 12:45:42 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'servo'@'172.18.0.1' (using password: YES) in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'servo', 'march27aug23', 'sampledata0201', 3306, '', 0)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#9 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'172.18.0.1' (using password: YES) in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#6 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-01-30 12:45:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.18.0.1' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_data`', [], false)
 3 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-30 12:46:02 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'servo'@'172.18.0.1' (using password: YES) in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'servo', 'march27aug23', 'sampledata0201', 3306, '', 0)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#9 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'172.18.0.1' (using password: YES) in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#6 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-01-30 12:46:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.18.0.1' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_data`', [], false)
 3 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 12:47:37 --> ErrorException: Undefined variable $user_data
in APPPATH\Views\crud_view.php on line 51.
 1 APPPATH\Views\crud_view.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $user_data', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php', 51)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('crud_view', [], true)
 5 APPPATH\Controllers\Crud.php(11): view('crud_view')
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 12:49:05 --> ErrorException: Undefined variable $user_data
in APPPATH\Views\crud_view.php on line 51.
 1 APPPATH\Views\crud_view.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $user_data', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php', 51)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('crud_view', [], true)
 5 APPPATH\Controllers\Crud.php(11): view('crud_view')
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 12:49:31 --> ErrorException: Undefined variable $user_data
in APPPATH\Views\crud_view.php on line 51.
 1 APPPATH\Views\crud_view.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $user_data', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php', 51)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('crud_view', [], true)
 5 APPPATH\Controllers\Crud.php(11): view('crud_view')
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 12:50:49 --> ErrorException: Undefined variable $tbl_data
in APPPATH\Views\crud_view.php on line 51.
 1 APPPATH\Views\crud_view.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $tbl_data', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php', 51)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('crud_view', [], true)
 5 APPPATH\Controllers\Crud.php(11): view('crud_view')
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-30 12:51:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'servo'@'172.18.0.1' (using password: YES) in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'servo', 'march27aug23', 'sampledata0201', 3306, '', 0)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#9 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'172.18.0.1' (using password: YES) in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#6 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-01-30 12:51:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.18.0.1' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_data`', [], false)
 3 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-30 12:52:24 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'servo'@'172.18.0.1' (using password: YES) in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('127.0.0.1', 'servo', 'march27aug23', 'sampledata0201', 3306, '', 0)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#9 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'172.18.0.1' (using password: YES) in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#6 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-01-30 12:52:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.18.0.1' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_data`', [], false)
 3 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-30 12:52:45 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('172.18.0.1', 'servo', 'march27aug23', 'sampledata0201', 3306, '', 0)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#9 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#6 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-01-30 12:52:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_data`', [], false)
 3 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-30 12:52:47 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('172.18.0.1', 'servo', 'march27aug23', 'sampledata0201', 3306, '', 0)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#9 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#6 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-01-30 12:52:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_data`', [], false)
 3 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-30 12:54:10 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('172.18.0.1', 'servo', 'march27aug23', 'sampledata0201', 3306, '', 0)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#9 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#6 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-01-30 12:54:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_data`', [], false)
 3 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-01-30 12:54:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'servo'@'172.18.0.1' (using password: YES) in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('192.168.100.19', 'servo', 'march27aug23', 'sampledata0201', 3306, '', 0)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#9 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'172.18.0.1' (using password: YES) in C:\xampp\htdocs\test-project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\test-project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\test-project\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\test-project\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\test-project\system\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\test-project\app\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
#6 C:\xampp\htdocs\test-project\system\CodeIgniter.php(941): App\Controllers\Crud->index()
#7 C:\xampp\htdocs\test-project\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
#8 C:\xampp\htdocs\test-project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\test-project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-01-30 12:54:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.18.0.1' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_data`', [], false)
 3 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1239): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Crud.php(15): CodeIgniter\BaseModel->paginate(10)
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:25:36 --> ErrorException: Undefined variable $model
in APPPATH\Controllers\Crud.php on line 69.
 1 APPPATH\Controllers\Crud.php(69): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $model', 'C:\\xampp\\htdocs\\test-project\\app\\Controllers\\Crud.php', 69)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:26:04 --> Error: Class "App\Controllers\SimpleXMLElement" not found
in APPPATH\Controllers\Crud.php on line 71.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:27:36 --> ErrorException: foreach() argument must be of type array|object, null given
in APPPATH\Controllers\Crud.php on line 75.
 1 APPPATH\Controllers\Crud.php(75): CodeIgniter\Debug\Exceptions->errorHandler(2, 'foreach() argument must be of type array|object, null given', 'C:\\xampp\\htdocs\\test-project\\app\\Controllers\\Crud.php', 75)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:28:44 --> TypeError: SimpleXMLElement::__construct(): Argument #1 ($data) must be of type string, array given
in APPPATH\Controllers\Crud.php on line 71.
 1 APPPATH\Controllers\Crud.php(71): SimpleXMLElement->__construct([...])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:39:06 --> TypeError: view(): Argument #2 ($data) must be of type array, SimpleXMLElement given, called in C:\xampp\htdocs\test-project\app\Controllers\Crud.php on line 84
in SYSTEMPATH\Common.php on line 1166.
 1 APPPATH\Controllers\Crud.php(84): view('crud_view', Object(SimpleXMLElement))
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:40:31 --> ErrorException: Undefined variable $tbl_data
in APPPATH\Views\crud_view.php on line 52.
 1 APPPATH\Views\crud_view.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $tbl_data', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php', 52)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('crud_view', [], true)
 5 APPPATH\Controllers\Crud.php(86): view('crud_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:40:44 --> ErrorException: Undefined variable $passedDate
in APPPATH\Views\xml_view.php on line 32.
 1 APPPATH\Views\xml_view.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $passedDate', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php', 32)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('xml_view', [], true)
 5 APPPATH\Controllers\Crud.php(86): view('xml_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:40:53 --> ErrorException: Undefined variable $passedData
in APPPATH\Views\xml_view.php on line 32.
 1 APPPATH\Views\xml_view.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $passedData', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php', 32)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('xml_view', [], true)
 5 APPPATH\Controllers\Crud.php(86): view('xml_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:40:54 --> ErrorException: Undefined variable $passedData
in APPPATH\Views\xml_view.php on line 32.
 1 APPPATH\Views\xml_view.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $passedData', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php', 32)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('xml_view', [], true)
 5 APPPATH\Controllers\Crud.php(86): view('xml_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:40:55 --> ErrorException: Undefined variable $passedData
in APPPATH\Views\xml_view.php on line 32.
 1 APPPATH\Views\xml_view.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $passedData', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php', 32)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('xml_view', [], true)
 5 APPPATH\Controllers\Crud.php(86): view('xml_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:40:55 --> ErrorException: Undefined variable $passedData
in APPPATH\Views\xml_view.php on line 32.
 1 APPPATH\Views\xml_view.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $passedData', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php', 32)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('xml_view', [], true)
 5 APPPATH\Controllers\Crud.php(86): view('xml_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:40:56 --> ErrorException: Undefined variable $passedData
in APPPATH\Views\xml_view.php on line 32.
 1 APPPATH\Views\xml_view.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $passedData', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php', 32)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('xml_view', [], true)
 5 APPPATH\Controllers\Crud.php(86): view('xml_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:40:56 --> ErrorException: Undefined variable $passedData
in APPPATH\Views\xml_view.php on line 32.
 1 APPPATH\Views\xml_view.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $passedData', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php', 32)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('xml_view', [], true)
 5 APPPATH\Controllers\Crud.php(86): view('xml_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:41:37 --> ErrorException: Undefined variable $passedData
in APPPATH\Views\xml_view.php on line 32.
 1 APPPATH\Views\xml_view.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $passedData', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php', 32)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('xml_view', [], true)
 5 APPPATH\Controllers\Crud.php(86): view('xml_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:42:22 --> ErrorException: Undefined variable $passedData
in APPPATH\Views\xml_view.php on line 32.
 1 APPPATH\Views\xml_view.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $passedData', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php', 32)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('xml_view', [], true)
 5 APPPATH\Controllers\Crud.php(86): view('xml_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:42:23 --> ErrorException: Undefined variable $passedData
in APPPATH\Views\xml_view.php on line 32.
 1 APPPATH\Views\xml_view.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $passedData', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php', 32)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('xml_view', [], true)
 5 APPPATH\Controllers\Crud.php(86): view('xml_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 13:44:28 --> ErrorException: foreach() argument must be of type array|object, string given
in APPPATH\Views\xml_view.php on line 32.
 1 APPPATH\Views\xml_view.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'foreach() argument must be of type array|object, string given', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php', 32)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\xml_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('xml_view', [], true)
 5 APPPATH\Controllers\Crud.php(86): view('xml_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->generateXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:01:27 --> ErrorException: Undefined property: App\Controllers\Crud::$load
in APPPATH\Controllers\Crud.php on line 92.
 1 APPPATH\Controllers\Crud.php(92): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Crud::$load', 'C:\\xampp\\htdocs\\test-project\\app\\Controllers\\Crud.php', 92)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->readXML()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:06:04 --> Error: Cannot call constructor
in APPPATH\Controllers\Crud.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\Crud->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:06:05 --> Error: Cannot call constructor
in APPPATH\Controllers\Crud.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\Crud->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:06:41 --> ErrorException: Undefined property: App\Controllers\Crud::$load
in APPPATH\Controllers\Crud.php on line 14.
 1 APPPATH\Controllers\Crud.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Crud::$load', 'C:\\xampp\\htdocs\\test-project\\app\\Controllers\\Crud.php', 14)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:06:42 --> ErrorException: Undefined property: App\Controllers\Crud::$load
in APPPATH\Controllers\Crud.php on line 14.
 1 APPPATH\Controllers\Crud.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Crud::$load', 'C:\\xampp\\htdocs\\test-project\\app\\Controllers\\Crud.php', 14)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:09:13 --> ErrorException: Undefined variable $tbl_data
in APPPATH\Views\crud_view.php on line 53.
 1 APPPATH\Views\crud_view.php(53): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $tbl_data', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php', 53)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('crud_view', [], true)
 5 APPPATH\Controllers\Crud.php(103): view('crud_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->readXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:10:13 --> ErrorException: Undefined variable $tbl_data
in APPPATH\Views\crud_view.php on line 53.
 1 APPPATH\Views\crud_view.php(53): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $tbl_data', 'C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php', 53)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\test-project\\app\\Views\\crud_view.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('crud_view', [], true)
 5 APPPATH\Controllers\Crud.php(103): view('crud_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->readXML()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:16:45 --> ErrorException: Undefined variable $xmlData
in APPPATH\Controllers\Crud.php on line 93.
 1 APPPATH\Controllers\Crud.php(93): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $xmlData', 'C:\\xampp\\htdocs\\test-project\\app\\Controllers\\Crud.php', 93)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->readerXML()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:23:59 --> ErrorException: Undefined property: App\Controllers\Crud::$simplexml
in APPPATH\Controllers\Crud.php on line 113.
 1 APPPATH\Controllers\Crud.php(113): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Crud::$simplexml', 'C:\\xampp\\htdocs\\test-project\\app\\Controllers\\Crud.php', 113)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->readXML()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:28:38 --> ErrorException: Undefined property: App\Controllers\Crud::$simplexml
in APPPATH\Controllers\Crud.php on line 113.
 1 APPPATH\Controllers\Crud.php(113): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Crud::$simplexml', 'C:\\xampp\\htdocs\\test-project\\app\\Controllers\\Crud.php', 113)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->readXML()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:29:24 --> TypeError: view(): Argument #2 ($data) must be of type array, bool given, called in C:\xampp\htdocs\test-project\app\Controllers\Crud.php on line 115
in SYSTEMPATH\Common.php on line 1166.
 1 APPPATH\Controllers\Crud.php(115): view('xml_reader', false)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->readXML()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:29:31 --> TypeError: view(): Argument #2 ($data) must be of type array, bool given, called in C:\xampp\htdocs\test-project\app\Controllers\Crud.php on line 115
in SYSTEMPATH\Common.php on line 1166.
 1 APPPATH\Controllers\Crud.php(115): view('xml_reader', false)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->readXML()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:31:28 --> Error: Call to a member function children() on bool
in APPPATH\Controllers\Crud.php on line 124.
 1 APPPATH\Controllers\Crud.php(115): App\Controllers\Crud->generateTable(false)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->readXML()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-01-30 14:32:13 --> ErrorException: simplexml_load_string(): Entity: line 1: parser error : XML declaration allowed only at the start of the document
in APPPATH\Controllers\Crud.php on line 114.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'simplexml_load_string(): Entity: line 1: parser error : XML declaration allowed only at the start of the document', 'C:\\xampp\\htdocs\\test-project\\app\\Controllers\\Crud.php', 114)
 2 APPPATH\Controllers\Crud.php(114): simplexml_load_string('            <?xml version="1.0"?>
<data><record><id>1</id><lastname>Guevarra</lastname><firstname>Aeia</firstname><middlename>Cabarubias</middlename><age>1</age><birthdate>2023-05-08</birthdate><status>Active</status></record><record><id>2</id><lastname>Evangelista</lastname><firstname>KLM</firstname><middlename>Dalusung</middlename><age>6</age><birthdate>2023-02-01</birthdate><status>Active</status></record><record><id>5</id><lastname>dfasdf</lastname><firstname>asdfasdf</firstname><middlename>dsfasdf</middlename><age>34</age><birthdate>2023-03-03</birthdate><status>Female</status></record><record><id>6</id><lastname>dfsfsdaf</lastname><firstname>fsdaf</firstname><middlename>sdfasdf</middlename><age>34</age><birthdate>2027-02-02</birthdate><status>Male</status></record><record><id>7</id><lastname>sfsdfsd</lastname><firstname>dsfsdf</firstname><middlename>defsdfsdf</middlename><age>5</age><birthdate>2021-12-02</birthdate><status>Male</status></record><record><id>8</id><lastname>Dela Cruz</lastname><firstname>Juan</firstname><middlename>Santos</middlename><age>23</age><birthdate>2015-04-02</birthdate><status>Female</status></record></data>')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Crud->readXML()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Crud))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
